version: '3.3'

services:
  postgres_service:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: hibernateDB
    ports:
      - "5432:5432"
